# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
#/run/numberOfThreads 4
/vis/disable
/run/initialize
#

/gps/particle e-
/gps/energy 1311 keV

# point source
#/gps/pos/type Point
#/gps/pos/centre 0. 0. 30.65 mm

/gps/pos/type Volume

/gps/pos/shape Cylinder
# hight of the Al Top Surface
/gps/pos/centre 0. 0. -0.1 cm
/gps/pos/radius 1.27 cm
/gps/pos/halfz 7.5 cm
#/gps/pos/confine World
#confine to physical volume "Shape7"

# angular distribution
/gps/ang/type iso 
/gps/number 1

/run/beamOn 1000
# 
#

